### ISSUE TITLE
【bug】使用报错和无法在线更新配置文件

### ISSUE THREAD

**Issue by qingchenhh** [gh0stkey/HaE#103]
burp版本：2023.1.1

Java版本：
java version "17.0.4" 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)

报错信息：
	at burp.hm6.b(Unknown Source)
	at burp.vxa.K(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.hm6.b(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "objects[6]" is null
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:67)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:91)
	at burp.y_g.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.pcl.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.t49.Z(Unknown Source)
	at burp.wwn.Z(Unknown Source)
	at burp.pls.s(Unknown Source)
	at burp._rg.L(Unknown Source)
	at burp._go.q(Unknown Source)
	at burp._rc.D(Unknown Source)
	at burp._rg.D(Unknown Source)
	at burp.t6z.G(Unknown Source)
	at burp.bn9.D(Unknown Source)
	at burp.bn9.v(Unknown Source)
	at burp.bn9.T(Unknown Source)
	at burp.u46.T(Unknown Source)
	at burp.v89.T(Unknown Source)
	at burp.hl8.T(Unknown Source)
	at burp._z1.J(Unknown Source)
	at burp.ho5.v(Unknown Source)
	at burp.vxa.K(Unknown Source)
	at burp.hm6.b(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "objects[6]" is null
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:67)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:91)
	at burp.y_g.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.pcl.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.t49.Z(Unknown Source)
	at burp.wwn.Z(Unknown Source)
	at burp.pls.s(Unknown Source)
	at burp._rg.L(Unknown Source)
	at burp._go.q(Unknown Source)
	at burp._rc.D(Unknown Source)
	at burp._rg.D(Unknown Source)
	at burp.t6z.G(Unknown Source)
	at burp.bn9.D(Unknown Source)
	at burp.bn9.v(Unknown Source)
	at burp.bn9.T(Unknown Source)
	at burp.u46.T(Unknown Source)
	at burp.v89.T(Unknown Source)
	at burp.hl8.T(Unknown Source)
	at burp._z1.J(Unknown Source)
	at burp.ho5.v(Unknown Source)
	at burp.vxa.K(Unknown Source)
	at burp.hm6.b(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "objects[6]" is null
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:67)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:91)
	at burp.y_g.handleHttpResponseReceived(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.pcl.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.t49.Z(Unknown Source)
	at burp.wwn.Z(Unknown Source)
	at burp.pls.s(Unknown Source)
	at burp.t6s.X(Unknown Source)
	at burp.bn9.D(Unknown Source)
	at burp.bn9.v(Unknown Source)
	at burp.bn9.T(Unknown Source)
	at burp.u46.T(Unknown Source)
	at burp.v89.T(Unknown Source)
	at burp.hl8.T(Unknown Source)
	at burp._z1.J(Unknown Source)
	at burp.ho5.v(Unknown Source)
	at burp.vxa.K(Unknown Source)
	at burp.hm6.b(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "objects[6]" is null
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:46)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:91)
	at burp.y_g.handleHttpRequestToBeSent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.pcl.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpRequestToBeSent(Unknown Source)
	at burp.t49.q(Unknown Source)
	at burp.wwn.q(Unknown Source)
	at burp.pls.d(Unknown Source)
	at burp.bn9.v(Unknown Source)
	at burp.bn9.T(Unknown Source)
	at burp.u46.T(Unknown Source)
	at burp.v89.T(Unknown Source)
	at burp.hl8.T(Unknown Source)
	at burp._z1.J(Unknown Source)
	at burp.ho5.v(Unknown Source)
	at burp.vxa.K(Unknown Source)
	at burp.hm6.b(Unknown Source)
	at burp.p_o.d(Unknown Source)
	at burp.p_o.j(Unknown Source)
	at burp.bta.h(Unknown Source)
	at burp.bta.L(Unknown Source)
	at burp.vup.a(Unknown Source)
	at burp.yxo.r(Unknown Source)
	at burp.yxo.s(Unknown Source)
	at burp.yxo.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
截图：
![image](https://user-images.githubusercontent.com/37011241/218615503-f6d66c18-da9a-4240-87e7-984895745d3e.png)

更新配置文件报错截图（网络正常，但是点击更新就失败了，不知道是不是写入配置文件时候的问题）：
![image](https://user-images.githubusercontent.com/37011241/218615689-0882dd82-729e-4a9a-81f7-711a925b3be2.png)

**Comment by gh0stkey** [comment]
从报错信息来看，就是配置信息那块出了问题，更新配置时全局代理翻个墙（配置文件在Github，也可以自行下载替换）

**Comment by gh0stkey** [comment]
https://github.com/gh0stkey/HaE/blob/gh-pages/Config.yml

**Comment by qingchenhh** [comment]
谢谢大佬的配置文件链接。但是，是我表达不清楚吗？是两个问题，第一个是使用不了，报错了，第二个才是配置文件没法在线更新。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gh0stkey/HaE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gh0stkey/HaE] 【bug】使用报错和无法在线更新配置文件 (Issue #103)





 
从报错信息来看，就是配置信息那块出了问题，更新配置时全局代理翻个墙（配置文件在Github，也可以自行下载替换）

**Comment by gh0stkey** [comment]
你弄下配置文件，应该就都好了

**Comment by qingchenhh** [comment]
> 你弄下配置文件，应该就都好了
真的好了，原来配置文件还会影响插件，谢谢大佬。

**Comment by gh0stkey** [comment]
客气～
