### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by timelessyu** [gh0stkey/HaE#109]
`java.lang.Exception: Extension class is not a recognized type
	at burp._f8.E(Unknown Source)
	at burp._f8.v(Unknown Source)
	at burp.lvh.d(Unknown Source)
	at burp.xqg.F(Unknown Source)
	at burp.ncn.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by gh0stkey** [comment]
麻烦看一下你的配置文件哈
