### ISSUE TITLE
burpsuit 2021.9  导入后报错

### ISSUE THREAD

**Issue by jwy0623** [gh0stkey/HaE#111]
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "objects[6]" is null
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:66)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:91)
	at burp.fh1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jwy0623** [comment]
hae 2.4.3

**Comment by gh0stkey** [comment]
看一下你的配置文件目录哦，先删掉再加载哈。
