### ISSUE TITLE
不能安装呢

### ISSUE THREAD

**Issue by nchulxc** [gh0stkey/HaE#125]
报错 JDK17 BURP版本是2023.6
java.lang.Exception: Extension class is not a recognized type
	at burp.Zs_x.Zw(Unknown Source)
	at burp.Zs_x.ZH(Unknown Source)
	at burp.Ziv6.ZG(Unknown Source)
	at burp.Zjav.Zf(Unknown Source)
	at burp.Zgbf.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gh0stkey** [comment]
可以看下其他的issue，检查下配置文件、HaE目录等等，谢谢。

**Comment by ddosi** [comment]
确实不能用.
java.lang.Exception: Extension class is not a recognized type
	at burp.Zuea.Zn(Unknown Source)
	at burp.Zuea.Zk(Unknown Source)
	at burp.Zu2b.ZK(Unknown Source)
	at burp.Zhsy.Zz(Unknown Source)
	at burp.Zxkk.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by No-Github** [comment]
同样
java version 17.0.2
burp 2023.6

<img width="751" alt="image" src="https://github.com/gh0stkey/HaE/assets/18167071/96929a76-93ae-4696-88c0-469fe11d437a">

**Comment by gh0stkey** [comment]
不能用的原因是因为HaE在配置文件进行了大的调整，如果一直使用的是官方规则库，可以直接删除所有配置文件，然后重新加载，会自动从官方规则库啦取最新规则。
