### ISSUE TITLE
2.4.8版本安装出现空指针报错

### ISSUE THREAD

**Issue by daovjnhs2** [gh0stkey/HaE#126]
java.lang.NullPointerException
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:98)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:39)
	at burp.ui.MainUI.<init>(MainUI.java:23)
	at burp.BurpExtender.<init>(BurpExtender.java:23)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at burp.xmu.V(Unknown Source)
	at burp.xmu.<init>(Unknown Source)
	at burp.ds.a(Unknown Source)
	at burp.ons.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
我的环境是jdk11，burp是2022.7

**Comment by WangQuFugui** [comment]
俺也一样

**Comment by gh0stkey** [comment]
删除配置文件，然后重新加载试一下

**Comment by daovjnhs2** [comment]
> 删除配置文件，然后重新加载试一下

删除了之后好了，感谢

**Comment by gh0stkey** [comment]
不客气～
