### ISSUE TITLE
两个版本的Release文件在加载的时候都出现这个错误提示

### ISSUE THREAD

**Issue by bingpo** [gh0stkey/HaE#127]
java.lang.Exception: Extension class is not a recognized type
	at burp.Ztb6.ZD(Unknown Source)
	at burp.Ztb6.ZD(Unknown Source)
	at burp.Zq3o.Z_(Unknown Source)
	at burp.Zwwr.Zm(Unknown Source)
	at burp.Zyto.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gh0stkey** [comment]
2.4.8版本为2.5过渡版，配置文件和规则文件变动较大，建议没有自定义规则的使用者可以删除配置文件然后重新加载最新的Jar包。

**Comment by bingpo** [comment]
ok，安装成功了
