### ISSUE TITLE
jdk17+burpsuite2023.10.1.2 error

### ISSUE THREAD

**Issue by hcjcn** [gh0stkey/HaE#129]
HaE-2.4.8-J9
java.lang.Exception: Extension class is not a recognized type
	at burp.Ztx6.Zn(Unknown Source)
	at burp.Ztx6.Zd(Unknown Source)
	at burp.Ztai.ZB(Unknown Source)
	at burp.Zx4k.ZV(Unknown Source)
	at burp.Zj1m.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kN6jq** [comment]
同样遇到

![image](https://github.com/gh0stkey/HaE/assets/27048404/5cc0a76f-5ade-4920-aa6c-f0c4b7da0106)
![image](https://github.com/gh0stkey/HaE/assets/27048404/5d9aac2f-9d79-4ca7-953b-0b994cd8fab3)

**Comment by ysdxj** [comment]
把原来的配置文件删了在添加

**Comment by kN6jq** [comment]
> 把原来的配置文件删了在添加

删掉了的   出现这个问题

**Comment by gh0stkey** [comment]
可以看下其他的ISSUE都是相同情况，删除原配置文件（Config.yml、Setting.yml）然后重新加载。

*nix用户的配置文件目录：~/.config/HaE/

Windows用户的配置文件目录：%USERPROFILE%/.config/HaE/

**Comment by gh0stkey** [comment]
@kN6jq 你遇到的这个情况是网络问题，建议联网+全局翻墙，实在不行，建议手动下载规则库放至对应配置目录下。
