### ISSUE TITLE
java.lang.Exception: Extension class is not a recognized type

### ISSUE THREAD

**Issue by badboycxcc** [gh0stkey/HaE#133]
j8 和j9 都是一样错误
```
java.lang.Exception: Extension class is not a recognized type
	at burp.Zs_x.Zw(Unknown Source)
	at burp.Zs_x.ZH(Unknown Source)
	at burp.Ziv6.ZG(Unknown Source)
	at burp.Zjav.Zf(Unknown Source)
	at burp.Zgbf.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by gh0stkey** [comment]
麻烦看一下这个ISSUE，谢谢：https://github.com/gh0stkey/HaE/issues/130
