### ISSUE TITLE
Comment和颜色显示异常

### ISSUE THREAD

**Issue by AmiaaaZ** [gh0stkey/HaE#134]
2.5.1最新版，HTTP History页面的Comment无显示，颜色标注也完全无了

![image-20231018135757289](https://amiz-1307622586.cos.ap-chongqing.myqcloud.com/images/image-20231018135757289.png)

上图里所有条目都应该有颜色标注和Comment，但是都没有；重启burp后颜色标注小部分恢复、但大部分url仍不显示颜色，Comment仍不显示

![image-20231018141516620](https://amiz-1307622586.cos.ap-chongqing.myqcloud.com/images/image-20231018141516620.png)

**Comment by gh0stkey** [comment]
BurpSuite啥版本，我使用的2023.10.3没出现这个问题，看下 Extensions里对应HaE是否有报错信息。

**Comment by AmiaaaZ** [comment]
> BurpSuite啥版本，我使用的2023.10.3没出现这个问题，看下 Extensions里对应HaE是否有报错信息。

burpsuite pro 2023.7.1

```
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 16
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at burp.BurpExtender.mergeComment(BurpExtender.java:147)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:128)
	at burp.Zses.handleHttpResponseReceived(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at burp.Zsm7.invoke(Unknown Source)
	at jdk.proxy5/jdk.proxy5.$Proxy87.handleHttpResponseReceived(Unknown Source)
	at burp.Zx5h.ZN(Unknown Source)
	at burp.Zh7.ZN(Unknown Source)
	at burp.Zlz8.ZN(Unknown Source)
	at burp.Zlex.Zn(Unknown Source)
	at burp.Znxx.ZX(Unknown Source)
	at burp.Znxy.Zi(Unknown Source)
	at burp.Znxk.ZF(Unknown Source)
	at burp.Znxx.ZF(Unknown Source)
	at burp.Zhvq.Zn(Unknown Source)
	at burp.Zh3b.ZR(Unknown Source)
	at burp.Zh3b.Ze(Unknown Source)
	at burp.Zh3b.ZK(Unknown Source)
	at burp.Zngr.ZK(Unknown Source)
	at burp.Zww.ZK(Unknown Source)
	at burp.Zhyk.ZK(Unknown Source)
	at burp.Zho.Zp(Unknown Source)
	at burp.Zcf.Zf(Unknown Source)
	at burp.Zcr.Zf(Unknown Source)
	at burp.Zh4i.Zn(Unknown Source)
	at burp.Zskz.ZW(Unknown Source)
	at burp.Ztir.Zv(Unknown Source)
	at burp.Ztir.ZD(Unknown Source)
	at burp.Zdqg.Za(Unknown Source)
	at burp.Zdqg.ZB(Unknown Source)
	at burp.Zt0z.Zc(Unknown Source)
	at burp.Zvhm.Zc(Unknown Source)
	at burp.Zvhm.ZT(Unknown Source)
	at burp.Zvhm.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 16
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at burp.BurpExtender.mergeComment(BurpExtender.java:147)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:128)
	at burp.Zses.handleHttpResponseReceived(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at burp.Zsm7.invoke(Unknown Source)
	at jdk.proxy5/jdk.proxy5.$Proxy87.handleHttpResponseReceived(Unknown Source)
	at burp.Zx5h.ZN(Unknown Source)
	at burp.Zh7.ZN(Unknown Source)
	at burp.Zlz8.ZN(Unknown Source)
	at burp.Zlex.Zn(Unknown Source)
	at burp.Znxx.ZX(Unknown Source)
	at burp.Znxy.Zi(Unknown Source)
	at burp.Znxk.ZF(Unknown Source)
	at burp.Znxx.ZF(Unknown Source)
	at burp.Zhvq.Zn(Unknown Source)
	at burp.Zh3b.ZR(Unknown Source)
	at burp.Zh3b.Ze(Unknown Source)
	at burp.Zh3b.ZK(Unknown Source)
	at burp.Zngr.ZK(Unknown Source)
	at burp.Zww.ZK(Unknown Source)
	at burp.Zhyk.ZK(Unknown Source)
	at burp.Zho.Zp(Unknown Source)
	at burp.Zcf.Zf(Unknown Source)
	at burp.Zcr.Zf(Unknown Source)
	at burp.Zh4i.Zn(Unknown Source)
	at burp.Zskz.ZW(Unknown Source)
	at burp.Ztir.Zv(Unknown Source)
	at burp.Ztir.ZD(Unknown Source)
	at burp.Zdqg.Za(Unknown Source)
	at burp.Zdqg.ZB(Unknown Source)
	at burp.Zt0z.Zc(Unknown Source)
	at burp.Zvhm.Zc(Unknown Source)
	at burp.Zvhm.ZT(Unknown Source)
	at burp.Zvhm.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 15
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4589)
	at java.base/java.lang.String.substring(String.java:2703)
	at burp.BurpExtender.mergeComment(BurpExtender.java:147)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:128)
	at burp.Zses.handleHttpResponseReceived(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at burp.Zsm7.invoke(Unknown Source)
	at jdk.proxy5/jdk.proxy5.$Proxy87.handleHttpResponseReceived(Unknown Source)
	at burp.Zx5h.ZN(Unknown Source)
	at burp.Zh7.ZN(Unknown Source)
	at burp.Zlz8.ZN(Unknown Source)
	at burp.Zlex.Zn(Unknown Source)
	at burp.Znxx.ZX(Unknown Source)
	at burp.Znxy.Zi(Unknown Source)
	at burp.Znxk.ZF(Unknown Source)
	at burp.Znxx.ZF(Unknown Source)
	at burp.Zhvq.Zn(Unknown Source)
	at burp.Zh3b.ZR(Unknown Source)
	at burp.Zh3b.Ze(Unknown Source)
	at burp.Zh3b.ZK(Unknown Source)
	at burp.Zngr.ZK(Unknown Source)
	at burp.Zww.ZK(Unknown Source)
	at burp.Zhyk.ZK(Unknown Source)
	at burp.Zho.Zp(Unknown Source)
	at burp.Zcf.Zf(Unknown Source)
	at burp.Zcr.Zf(Unknown Source)
	at burp.Zh4i.Zn(Unknown Source)
	at burp.Zskz.ZW(Unknown Source)
	at burp.Ztir.Zv(Unknown Source)
	at burp.Ztir.ZD(Unknown Source)
	at burp.Zdqg.Za(Unknown Source)
	at burp.Zdqg.ZB(Unknown Source)
	at burp.Zt0z.Zc(Unknown Source)
	at burp.Zvhm.Zc(Unknown Source)
	at burp.Zvhm.ZT(Unknown Source)
	at burp.Zvhm.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by gh0stkey** [comment]
麻烦师傅加我下微信：EVILCHEN__，确实存在问题，我重新编译了一版，给您测试下。
