### ISSUE TITLE
加载UI报java.lang.NullPointerException错

### ISSUE THREAD

**Issue by Chestnuts4** [gh0stkey/HaE#139]
环境：
burp 21.8.2
java 11

gradle配置和依赖
```gradle
plugins {
    id("java")
}

group = "burp"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}


//tasks.withType(JavaCompile){
//    options.encoding="UTF-8"
//}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    // https://mvnrepository.com/artifact/net.portswigger.burp.extender/burp-extender-api
    implementation("net.portswigger.burp.extender:burp-extender-api:2.2")
    implementation("dk.brics:automaton:1.12-4")
    // https://mvnrepository.com/artifact/org.yaml/snakeyaml
    implementation("org.yaml:snakeyaml:1.28")
    implementation("net.sourceforge.jregex:jregex:1.2_01")
}

tasks.test {
    useJUnitPlatform()
}
```
idea配置
![image](https://github.com/gh0stkey/HaE/assets/116432652/e4c7a5d6-88c0-47ca-8df6-5a8c214c88db)

在build -> artifacts 构建之后，加载入bp内报错如下，看起来是BurpExtender类没有实例化导致的。
```
java.lang.NullPointerException
	at burp.fkh.addSuiteTab(Unknown Source)
	at burp.b8s.addSuiteTab(Unknown Source)
	at burp.gz0.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:67)
	at burp.BurpExtender$1.run(BurpExtender.java:54)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

我自己一个拓展的demo和你代码类似，就不会报错，但把HaE代码改成下面类似的仍然是这个错误
```java
   @Override
    public void registerExtenderCallbacks(IBurpExtenderCallbacks callbacks) {

        BurpExtender.helpers = callbacks.getHelpers();
        BurpExtender.callbacks = callbacks;
        callbacks.setExtensionName(String.format("%s %s", name, version));

        // 初始化UI
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                initUI();
            }
        });
        // 注册监听
        callbacks.registerHttpListener(BurpExtender.this);
    }


    private void initUI() {
        mainGUI = new MainUI();
        callbacks.addSuiteTab(this);


        callbacks.printOutput("load success");
        callbacks.customizeUiComponent(mainGUI.$$$getRootComponent$$$());

    }

```

能力有限没看出来为什么会这样

**Comment by gh0stkey** [comment]
使用gradle fastjar进行编译，版本可看：https://github.com/gh0stkey/HaE/issues/138
