### ISSUE TITLE
[BUG] Socket closed

### ISSUE THREAD

**Issue by lnm3000** [gh0stkey/HaE#150]
## 使用环境

```
HaE版本：2.5.8
BurpSuite版本：1.7.37
JDK版本：1.8.0_333
操作系统版本：mac OS 12.4
```

## 问题详情

问题描述：Burp Suite未加载任何插件的情况下使用，可以两天不关闭Brup Suite进程，一直用。
但当加载了 HaE 插件后（且仅加载了 HaE 这一个插件），基本上就是使用大概1个小时左右。任何经过 Burp Suite的数据包都发不出去了，提示 “Socket closed”，如图一。即使是使用 Repeater 模块直接重放数据库，同样提示 “Socket closed”。

出现的场景：
图一：
<img width="679" alt="image" src="https://github.com/gh0stkey/HaE/assets/22117516/7fd4d77b-f436-4472-a777-4db442c18c8e">
图二：
<img width="1680" alt="image" src="https://github.com/gh0stkey/HaE/assets/22117516/6315a6cf-8042-4169-8817-3e79830f73ab">

## 解决建议

无。

**Comment by gh0stkey** [comment]
麻烦师傅控制台启动一下BurpSuite的Jar包然后看一下是否有报错信息。

**Comment by lnm3000** [comment]
好的，key师傅，按您的要求，从控制台使用以下命令启动 Burp Suite ：
java -Xbootclasspath/p:burp-loader-keygen.jar -jar burpsuite_pro_v1.7.37.jar

在未加载其他任何插件的情况下，仅加载 HaE，控制台直接触发以下错误：
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.b(Unknown Source)
	at burp.jke.a(Unknown Source)
	at burp.v0d.addSuiteTab(Unknown Source)
	at burp.nb.addSuiteTab(Unknown Source)
	at burp.aph.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:67)
	at burp.BurpExtender.access$000(BurpExtender.java:24)
	at burp.BurpExtender$1.run(BurpExtender.java:54)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.b(Unknown Source)
	at burp.jke.a(Unknown Source)
	at burp.v0d.addSuiteTab(Unknown Source)
	at burp.nb.addSuiteTab(Unknown Source)
	at burp.aph.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:67)
	at burp.BurpExtender.access$000(BurpExtender.java:24)
	at burp.BurpExtender$1.run(BurpExtender.java:54)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.b(Unknown Source)
	at burp.jke.a(Unknown Source)
	at burp.v0d.addSuiteTab(Unknown Source)
	at burp.nb.addSuiteTab(Unknown Source)
	at burp.aph.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:67)
	at burp.BurpExtender.access$000(BurpExtender.java:24)
	at burp.BurpExtender$1.run(BurpExtender.java:54)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at burp.core.processor.MessageProcessor.processRequestMessage(MessageProcessor.java:41)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:229)
	at burp.emb.b(Unknown Source)
	at burp.chb.b(Unknown Source)
	at burp.chb.a(Unknown Source)
	at burp.igf.a(Unknown Source)
	at burp.igf.b(Unknown Source)
	at burp.jke.a(Unknown Source)
	at burp.v0d.addSuiteTab(Unknown Source)
	at burp.nb.addSuiteTab(Unknown Source)
	at burp.aph.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:67)
	at burp.BurpExtender.access$000(BurpExtender.java:24)
	at burp.BurpExtender$1.run(BurpExtender.java:54)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:178)
	at burp.core.processor.MessageProcessor.processMessage(MessageProcessor.java:27)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:133)
	at burp.iki.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)

**Comment by gh0stkey** [comment]
好的，感谢反馈，这个问题下个版本修复。
