### ISSUE TITLE
[BUG] 导入Burp时报错

### ISSUE THREAD

**Issue by Ryan0lb** [gh0stkey/HaE#164]
## 使用环境

```
HaE版本：2.6.1
是否有自定义的HaE规则：
BurpSuite版本：
JDK版本：1.8
操作系统版本：win10
```

## 问题详情

导入Burp时报错

问题描述：

![image](https://github.com/gh0stkey/HaE/assets/15329046/4dc406b2-35a6-4234-9c0e-998f4951e418)

**Comment by gh0stkey** [comment]
麻烦提issue之前可以翻一下之前的历史记录：https://github.com/gh0stkey/HaE/issues/130#issuecomment-1760711586

**Comment by Ryan0lb** [comment]
dgsdg5s4dgs5g4sdgミドっぱくラバニラサダウのブはとてもおいしそうなりんかマカョ

**Comment by bdtl** [comment]
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1649)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1495)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1458)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:255)
	at burp.Z_mq.Zm(Unknown Source)
	at burp.Z_mq.ZH(Unknown Source)
	at burp.Zs_2.ZG(Unknown Source)
	at burp.Zs22.ZV(Unknown Source)
	at burp.Zaye.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Ryan0lb** [comment]
dgsdg5s4dgs5g4sdgミドっぱくラバニラサダウのブはとてもおいしそうなりんかマカョ
