### ISSUE TITLE
[BUG] 导入安装时报错

### ISSUE THREAD

**Issue by homelanmder** [gh0stkey/HaE#165]
## 使用环境

```
HaE版本：2.6.1
是否有自定义的HaE规则：无
BurpSuite版本：2020.12.1
JDK版本：1.8.0_181
操作系统版本：win 11
```

## 问题详情

问题描述：安装直接抛出错误
java.lang.NullPointerException
	at burp.aqd.makeHttpRequest(Unknown Source)
	at burp.lq.makeHttpRequest(Unknown Source)
	at burp.a3i.makeHttpRequest(Unknown Source)
	at burp.rule.utils.RuleTool.lambda$getRulesFromSite$0(RuleTool.java:26)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.NullPointerException
	at burp.config.ConfigLoader.getRules(ConfigLoader.java:117)
	at burp.config.ConfigLoader.<init>(ConfigLoader.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.avu.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

![image](https://github.com/gh0stkey/HaE/assets/53993222/fe8635ac-ff73-49b1-8957-f31892b69d11)
![image](https://github.com/gh0stkey/HaE/assets/53993222/5ac163f6-4a00-4fe7-baf3-20ccf86be766)

**Comment by gh0stkey** [comment]
麻烦提issue之前可以翻一下之前的历史记录：https://github.com/gh0stkey/HaE/issues/130#issuecomment-1760711586
