### ISSUE TITLE
[BUG] 最新版无高亮显示

### ISSUE THREAD

**Issue by AmiaaaZ** [gh0stkey/HaE#177]
## 使用环境

```
HaE版本：3.0
是否有自定义的HaE规则：无
BurpSuite版本：burpsuite pro v2024.4.1
JDK版本：java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
操作系统版本：win10专业版
```

## 问题详情

问题描述：HaE插件报错，同时使用的插件有CRLFScan, Logger++, BypassPro
```
burp.api.montoya.http.message.requests.MalformedRequestException: URL is invalid.
	at burp.Zsc2.url(Unknown Source)
	at burp.Zalb.url(Unknown Source)
	at hae.instances.http.HttpMessageHandler.handleHttpRequestToBeSent(HttpMessageHandler.java:44)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy49.handleHttpRequestToBeSent(Unknown Source)
	at burp.Zv1e.ZD(Unknown Source)
	at burp.Zso_.ZD(Unknown Source)
	at burp.Zfbd.ZD(Unknown Source)
	at burp.Zp96.Zy(Unknown Source)
	at burp.Zpcs.Zf(Unknown Source)
	at burp.Zpcs.ZA(Unknown Source)
	at burp.Zf0_.ZA(Unknown Source)
	at burp.Zuyt.ZA(Unknown Source)
	at burp.Zg_b.ZA(Unknown Source)
	at burp.Zvc4.ZH(Unknown Source)
	at burp.Znx.ZD(Unknown Source)
	at burp.Znb.ZD(Unknown Source)
	at burp.Zuke.ZK(Unknown Source)
	at burp.Zslu.ZX(Unknown Source)
	at burp.Zslu.ZE(Unknown Source)
	at burp.Zfv4.ZM(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at burp.Zfv4.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zdjo.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy48.sendRequest(Unknown Source)
	at burp.Zc3u.makeHttpRequest(Unknown Source)
	at burp.Zzt4.makeHttpRequest(Unknown Source)
	at burp.Zz7t.makeHttpRequest(Unknown Source)
	at burp.Zz7t.makeHttpRequest(Unknown Source)
	at burp.Zziz.makeHttpRequest(Unknown Source)
	at Main.BypassMain$Run_request.run(BypassMain.java:450)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
关闭其它插件仅加载HaE，Extensions页面没有报错信息，但仍然没有高亮，Proxy的响应部分和Databoard标签无统计

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
请查看你的规则是否有问题

**Comment by AmiaaaZ** [comment]
规则全部是默认的 无修改新增

**Comment by AmiaaaZ** [comment]
把\.config\HaE下的文件删掉又重新加载插件就正常了 问题已解决

**Comment by gh0stkey** [comment]
好的，感谢关注与支持！祝您用了就有洞，洞洞是高危。

**Comment by JordanA54** [comment]
> 把.config\HaE下的文件删掉又重新加载插件就正常了 问题已解决

谢谢，我看了你的评论，我删除了hae下的文件重新加载插件也解决了
