### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lufei101** [gh0stkey/HaE#178]
## 使用环境

```
HaE版本：HaE3.0
是否有自定义的HaE规则：无
BurpSuite版本：burp最新版2024.4.1
JDK版本：本机1.8，burp启动jdk21
操作系统版本：windows
```

## 问题详情

问题描述：

![image](https://github.com/gh0stkey/HaE/assets/93892809/06dd8cdf-7b83-42e7-9d52-63a19a385449)

```
java.net.UnknownHostException: raw.githubusercontent.com
at burp.Zd1_.Zh(Unknown Source)
at burp.Zcip.Zh(Unknown Source)
at burp.Zpcs.ZA(Unknown Source)
at burp.Zf0_.ZA(Unknown Source)
at burp.Zuyt.ZA(Unknown Source)
at burp.Zg_b.ZA(Unknown Source)
at burp.Zvc4.ZH(Unknown Source)
at burp.Znx.ZD(Unknown Source)
at burp.Znb.ZD(Unknown Source)
at burp.Zuke.ZK(Unknown Source)
at burp.Zslu.ZX(Unknown Source)
at burp.Zslu.ZE(Unknown Source)
at burp.Zfv4.ZM(Unknown Source)
at burp.Zfv4.sendRequest(Unknown Source)
at burp.Zfv4.sendRequest(Unknown Source)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at burp.Zdjo.invoke(Unknown Source)
at jdk.proxy2/jdk.proxy2.$Proxy32.sendRequest(Unknown Source)
at burp.Ztg.sendRequest(Unknown Source)
at hae.utils.config.ConfigLoader.pullRules(ConfigLoader.java:184)
at hae.utils.config.ConfigLoader$1.run(ConfigLoader.java:170)
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
at hae.component.Main.getImageIcon(Main.java:81)
at hae.component.Main.initComponents(Main.java:40)
at hae.component.Main.<init>(Main.java:26)
at hae.HaE.initialize(HaE.java:34)
at burp.Zavu.ZG(Unknown Source)
at burp.Zk.Ze(Unknown Source)
at burp.Zr.lambda$initialiseOnNewThread$0(Unknown Source)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
```
出现的场景：删除.config/HaE文件夹重新安装时出现

## 解决建议

无。

**Comment by Lufei101** [comment]
原因应该是https://raw.githubusercontent.com/gh0stkey/HaE/gh-pages/Rules.yml访问不到导致不能正常在本地生成，所以直接在目录下新建Rules.yml手动粘贴网站内容就可以了。

**Comment by gh0stkey** [comment]
网络问题，不属于BUG，谢谢反馈。
