### ISSUE TITLE
[BUG] burp2024.3.1.4加载hae3.0.1版本报错

### ISSUE THREAD

**Issue by dggsec** [gh0stkey/HaE#183]
## 使用环境

```
HaE版本：3.0.1
是否有自定义的HaE规则：有
BurpSuite版本：2024.3.1.4
JDK版本：21
操作系统版本：win11
```

## 问题详情

问题描述：加载hae报错
java.net.UnknownHostException: raw.githubusercontent.com
	at burp.Zj21.ZT(Unknown Source)
	at burp.Zyt5.ZT(Unknown Source)
	at burp.Zl82.Zk(Unknown Source)
	at burp.Zycw.Zk(Unknown Source)
	at burp.Zx41.Zk(Unknown Source)
	at burp.Zqge.Zk(Unknown Source)
	at burp.Zjx8.Zb(Unknown Source)
	at burp.Za9n.Za(Unknown Source)
	at burp.Za9_.Za(Unknown Source)
	at burp.Zi8_.Zm(Unknown Source)
	at burp.Zl00.Za(Unknown Source)
	at burp.Zl00.ZD(Unknown Source)
	at burp.Zqw6.ZC(Unknown Source)
	at burp.Zqw6.sendRequest(Unknown Source)
	at burp.Zqw6.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zoju.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy19.sendRequest(Unknown Source)
	at burp.Zq55.sendRequest(Unknown Source)
	at hae.utils.config.ConfigLoader.pullRules(ConfigLoader.java:184)
	at hae.utils.config.ConfigLoader$1.run(ConfigLoader.java:170)
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
	at hae.component.Main.getImageIcon(Main.java:81)
	at hae.component.Main.initComponents(Main.java:40)
	at hae.component.Main.<init>(Main.java:26)
	at hae.HaE.initialize(HaE.java:34)
	at burp.Zil.Zh(Unknown Source)
	at burp.Zikh.Zk(Unknown Source)
	at burp.Ziko.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
UnknownHostException，请挂代理。

**Comment by dggsec** [comment]
java.lang.ClassNotFoundException: org.yaml.snakeyaml.tokens.Token
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchStreamStart(ScannerImpl.java:612)
	at org.yaml.snakeyaml.scanner.ScannerImpl.<init>(ScannerImpl.java:230)
	at org.yaml.snakeyaml.parser.ParserImpl.<init>(ParserImpl.java:136)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:434)
	at hae.utils.config.ConfigLoader.getExcludeSuffix(ConfigLoader.java:102)
	at hae.component.config.Config.initComponents(Config.java:46)
	at hae.component.config.Config.<init>(Config.java:21)
	at hae.component.Main.initComponents(Main.java:69)
	at hae.component.Main.<init>(Main.java:26)
	at hae.HaE.initialize(HaE.java:34)
	at burp.Zil.Zh(Unknown Source)
	at burp.Zikh.Zk(Unknown Source)
	at burp.Ziko.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

请问这个报错是为什么呢？

**Comment by aikeonline** [comment]
解决了吗？
