### ISSUE TITLE
[BUG] 装不上

### ISSUE THREAD

**Issue by Lanxiy7th** [gh0stkey/HaE#186]
java.net.UnknownHostException: raw.githubusercontent.com
	at burp.Zdwo.ZT(Unknown Source)
	at burp.Zd9j.ZT(Unknown Source)
	at burp.Zl4_.Zy(Unknown Source)
	at burp.Zlj6.Zy(Unknown Source)
	at burp.Zmrf.Zy(Unknown Source)
	at burp.Zuew.Zy(Unknown Source)
	at burp.Zuqh.ZB(Unknown Source)
	at burp.Zuzx.ZY(Unknown Source)
	at burp.Zuz4.ZY(Unknown Source)
	at burp.Zxt6.ZA(Unknown Source)
	at burp.Zdzj.Zo(Unknown Source)
	at burp.Zdzj.Zs(Unknown Source)
	at burp.Zij2.ZI(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at burp.Zij2.sendRequest(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Zx_5.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy21.sendRequest(Unknown Source)
	at burp.Zk78.sendRequest(Unknown Source)
	at hae.utils.config.ConfigLoader.pullRules(ConfigLoader.java:180)
	at hae.utils.config.ConfigLoader$1.run(ConfigLoader.java:166)
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
	at hae.component.Main.getImageIcon(Main.java:81)
	at hae.component.Main.initComponents(Main.java:40)
	at hae.component.Main.<init>(Main.java:26)
	at hae.HaE.initialize(HaE.java:34)
	at burp.Zdsi.Zr(Unknown Source)
	at burp.Zi56.Zp(Unknown Source)
	at burp.Zi58.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by gh0stkey** [comment]
在使用一款开源工具之前，可以先仔细看一下它的README：https://github.com/gh0stkey/HaE?tab=readme-ov-file#%E9%A1%B9%E7%9B%AE%E4%BB%8B%E7%BB%8D

<img width="848" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/8b064295-5ab9-4a8f-a4d4-83831708ec3f">

其次遇到相同问题，可以关键词搜索历史ISSUES：https://github.com/gh0stkey/HaE/issues?q=UnknownHostException

<img width="1284" alt="image" src="https://github.com/gh0stkey/HaE/assets/24655118/ecf9f4ae-3c5a-4ae4-ae48-0714d4cec4ee">

尊重开源项目，从你我做起。节省大家时间，从你我开始。
