### ISSUE TITLE
[Bug] mac下装载失败

### ISSUE THREAD

**Issue by daydust** [gh0stkey/HaE#189]
## 使用环境

```
HaE 版本：3.0.2
有无自定义规则：无
BurpSuite 版本：2024.3.1
操作系统版本：macos
有无仔细阅读README：有
```

在Burpsuite2024.3.1中安装hae3.0.2时，爆出如下错误

java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
	at hae.component.Main.getImageIcon(Main.java:81)
	at hae.component.Main.initComponents(Main.java:40)
	at hae.component.Main.<init>(Main.java:26)
	at hae.HaE.initialize(HaE.java:34)
	at burp.Zzh9.Zw(Unknown Source)
	at burp.Z_kv.Zb(Unknown Source)
	at burp.Z_k3.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by gh0stkey** [comment]
检查你下载的Jar包是不是缺少logo的png文件
