### ISSUE TITLE
HAE安装后显示找不到burp.api.montoya.ui.editor.HttpRequestEditor.uiComponent()方法

### ISSUE THREAD

**Issue by 2993134136** [gh0stkey/HaE#201]
![image](https://github.com/user-attachments/assets/968ac637-2eb4-4cdd-85ed-c4aa166a0a9b)
请问该怎么去解决
报错信息如下：
java.lang.NoSuchMethodError: 'java.awt.Component burp.api.montoya.ui.editor.HttpRequestEditor.uiComponent()'
	at hae.component.board.message.MessageTableModel.<init>(MessageTableModel.java:47)
	at hae.HaE.initialize(HaE.java:33)
	at burp.ku3.a(Unknown Source)
	at burp.l8s.w(Unknown Source)
	at burp.l83.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:83

**Comment by gh0stkey** [comment]
HaE 3.0版本开始采用Montoya API进行开发，使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。
