### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by f12sec** [gh0stkey/HaE#202]
## 使用环境
windows 使用  java版本17.0.5
```
HaE 版本：
有无自定义规则：无自定义规则
BurpSuite 版本：2022.1
操作系统版本：windiws 11
有无仔细阅读README：已认真阅读过文档
```
## 问题详情
两台电脑尝试 都是此错误，两台电脑都是windows11
尝试过版本 hae 3.3 hae 3.3.1 hae3.2版本 burp都无法加载 错误如下：
问题描述：
 burp都无法加载 错误如下：
出现的场景：
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.c6t.a(Unknown Source)
	at burp.c6t.<init>(Unknown Source)
	at burp.izp.a(Unknown Source)
	at burp.ah0.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
![image](https://github.com/user-attachments/assets/c3ea8068-0ff0-4c5d-9317-93ec7bd2362b)

## 解决建议

无。

**Comment by gh0stkey** [comment]
兄弟，README仔细读：`HaE 3.0版本开始采用Montoya API进行开发，使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。
`
