### ISSUE TITLE
[BUG] 问题标题

### ISSUE THREAD

**Issue by rainbowdrizzle** [gh0stkey/HaE#204]
## 使用环境

```
HaE 版本：3.3.1
有无自定义规则：无
BurpSuite 版本：2024.7.3
操作系统版本：win10
有无仔细阅读README：有
```

## 问题详情

问题描述：无法安装插件
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1649)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1495)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1458)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:255)
	at burp.Za8c.Zv(Unknown Source)
	at burp.Za8c.ZG(Unknown Source)
	at burp.Zsp5.ZW(Unknown Source)
	at burp.Za0y.Zn(Unknown Source)
	at burp.Zsfe.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

出现的场景：

## 解决建议

无。

**Comment by gh0stkey** [comment]
兄弟，你的报错内容：`java.util.zip.ZipException: zip END header not found`，你的JAR包都没下载完整就导入了。
