### ISSUE TITLE
BrupSuite V2021.4 版本无法高亮显示问题

### ISSUE THREAD

**Issue by al0ne** [gh0stkey/HaE#21]
**版本环境**
系统环境：Windows10+JDK11
Burpsuite版本：BrupSuite V2021.4
Hae版本：最新版

**问题描述：**
插件命中后无法高亮显示
我在这里设置了匹配到mysql报错显示为红色，但是在burp的代理历史中无法高亮显示
![image](https://user-images.githubusercontent.com/13449320/124362222-3e9a3300-dc66-11eb-8af3-9e65d2bc865a.png)
![image](https://user-images.githubusercontent.com/13449320/124362190-17436600-dc66-11eb-8b03-dcfe580a0ae8.png)

**报错信息**
java.lang.NullPointerException
	at burp.dbx.b(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fm9.b(Unknown Source)
	at burp.fm9.c(Unknown Source)
	at burp.fns.a(Unknown Source)
	at burp.g61.addSuiteTab(Unknown Source)
	at burp.ajw.addSuiteTab(Unknown Source)
	at burp.cmy.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:56)
	at burp.BurpExtender.access$000(BurpExtender.java:18)
	at burp.BurpExtender$1.run(BurpExtender.java:47)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.dbx.b(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fm9.b(Unknown Source)
	at burp.fm9.c(Unknown Source)
	at burp.fns.a(Unknown Source)
	at burp.g61.addSuiteTab(Unknown Source)
	at burp.ajw.addSuiteTab(Unknown Source)
	at burp.cmy.addSuiteTab(Unknown Source)
	at burp.BurpExtender.initialize(BurpExtender.java:56)
	at burp.BurpExtender.access$000(BurpExtender.java:18)
	at burp.BurpExtender$1.run(BurpExtender.java:47)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.dbx.b(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fm9.a(Unknown Source)
	at burp.g1z.a(Unknown Source)
	at burp.fge.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.fgm.g(Unknown Source)
	at burp.fgm.b(Unknown Source)
	at burp.fgm.a(Unknown Source)
	at burp.fgm.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Request cannot be null
	at burp.ek2.analyzeRequest(Unknown Source)
	at burp.fhv.analyzeRequest(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:141)
	at burp.dbx.b(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.fge.a(Unknown Source)
	at burp.f39.a(Unknown Source)
	at burp.ex5.lambda$nodeSelected$9(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by al0ne** [comment]
更新 我发现匹配位置使用response body的时候就不高亮。response就高亮。是这个原因吗

**Comment by gh0stkey** [comment]
代码逻辑的错误，目前已经更新修复BUG，感谢！
最新版本：https://github.com/gh0stkey/HaE/releases/tag/2.0.5

**Comment by gh0stkey** [comment]
@1694936784nm HaE 3.0版本开始采用Montoya API进行开发，使用新版HaE需要升级你的BurpSuite版本（>=2023.12.1）。
