### ISSUE TITLE
导入BP出错

### ISSUE THREAD

**Issue by azhibing** [gh0stkey/HaE#22]
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at burp.yaml.LoadRule.getConfig(LoadRule.java:74)
	at burp.ui.MainUI.initComponents(MainUI.java:179)
	at burp.ui.MainUI.<init>(MainUI.java:24)
	at burp.BurpExtender.<init>(BurpExtender.java:19)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.gsu.a(Unknown Source)
	at burp.gsu.<init>(Unknown Source)
	at burp.baa.a(Unknown Source)
	at burp.em3.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:162)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
	... 31 more

**Comment by gh0stkey** [comment]
BurpSuite版本，HaE版本，麻烦说明一下，导入之后是不可以使用了吗，另外检查一下BurpSuite Jar包同级目录下是否与Setting.yaml以及对应的内容指向的Config的路径文件是否存在。

**Comment by gh0stkey** [comment]
7天未回复，关闭issue。
