### ISSUE TITLE
[BUG] 加载插件BP报错

### ISSUE THREAD

**Issue by ouoer** [gh0stkey/HaE#224]
![image](https://github.com/user-attachments/assets/91abe5b6-ea53-45c0-af05-d7c9a28f8639)
	
at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'
	at hae.utils.http.HttpUtils.verifyHttpRequestResponse(HttpUtils.java:53)
	at hae.instances.http.HttpMessageHandler.handleHttpResponseReceived(HttpMessageHandler.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zzew.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zc6t.Zf(Unknown Source)
	at burp.Zosp.Zf(Unknown Source)
	at burp.Zzwh.Zf(Unknown Source)
	at burp.Zanw.Z_(Unknown Source)
	at burp.Zw1.Zu(Unknown Source)
	at burp.Zw_.ZK(Unknown Source)
	at burp.Zwu.Zy(Unknown Source)
	at burp.Zw1.Zy(Unknown Source)
	at burp.Zkwv.Zu(Unknown Source)
	at burp.Za_t.Zp(Unknown Source)
	at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'
	at hae.utils.http.HttpUtils.verifyHttpRequestResponse(HttpUtils.java:53)
	at hae.instances.http.HttpMessageHandler.handleHttpResponseReceived(HttpMessageHandler.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zzew.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zc6t.Zf(Unknown Source)
	at burp.Zosp.Zf(Unknown Source)
	at burp.Zzwh.Zf(Unknown Source)
	at burp.Zanw.Z_(Unknown Source)
	at burp.Zw1.Zu(Unknown Source)
	at burp.Zw_.ZK(Unknown Source)
	at burp.Zwu.Zy(Unknown Source)
	at burp.Zw1.Zy(Unknown Source)
	at burp.Zkwv.Zu(Unknown Source)
	at burp.Za_t.Zp(Unknown Source)
	at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'
	at hae.utils.http.HttpUtils.verifyHttpRequestResponse(HttpUtils.java:53)
	at hae.instances.http.HttpMessageHandler.handleHttpResponseReceived(HttpMessageHandler.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zzew.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zc6t.Zf(Unknown Source)
	at burp.Zosp.Zf(Unknown Source)
	at burp.Zzwh.Zf(Unknown Source)
	at burp.Zanw.Z_(Unknown Source)
	at burp.Zw1.Zu(Unknown Source)
	at burp.Zw_.ZK(Unknown Source)
	at burp.Zwu.Zy(Unknown Source)
	at burp.Zw1.Zy(Unknown Source)
	at burp.Zkwv.Zu(Unknown Source)
	at burp.Za_t.Zp(Unknown Source)
	at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'
	at hae.utils.http.HttpUtils.verifyHttpRequestResponse(HttpUtils.java:53)
	at hae.instances.http.HttpMessageHandler.handleHttpResponseReceived(HttpMessageHandler.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zzew.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zc6t.Zf(Unknown Source)
	at burp.Zosp.Zf(Unknown Source)
	at burp.Zzwh.Zf(Unknown Source)
	at burp.Zanw.Z_(Unknown Source)
	at burp.Zw1.Zu(Unknown Source)
	at burp.Zw_.ZK(Unknown Source)
	at burp.Zwu.Zy(Unknown Source)
	at burp.Zw1.Zy(Unknown Source)
	at burp.Zkwv.Zu(Unknown Source)
	at burp.Za_t.Zp(Unknown Source)
	at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.NoSuchMethodError: 'java.lang.String burp.api.montoya.http.message.requests.HttpRequest.fileExtension()'
	at hae.utils.http.HttpUtils.verifyHttpRequestResponse(HttpUtils.java:53)
	at hae.instances.http.HttpMessageHandler.handleHttpResponseReceived(HttpMessageHandler.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zzew.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy22.handleHttpResponseReceived(Unknown Source)
	at burp.Zc6t.Zf(Unknown Source)
	at burp.Zosp.Zf(Unknown Source)
	at burp.Zzwh.Zf(Unknown Source)
	at burp.Zanw.Z_(Unknown Source)
	at burp.Zw1.Zu(Unknown Source)
	at burp.Zw_.ZK(Unknown Source)
	at burp.Zwu.Zy(Unknown Source)
	at burp.Zw1.Zy(Unknown Source)
	at burp.Zkwv.Zu(Unknown Source)
	at burp.Za_t.Zp(Unknown Source)
	at burp.Za_t.Zr(Unknown Source)
	at burp.Za_t.ZI(Unknown Source)
	at burp.Z_uq.ZI(Unknown Source)
	at burp.Zjt_.ZI(Unknown Source)
	at burp.Zmv.ZI(Unknown Source)
	at burp.Zk_f.ZL(Unknown Source)
	at burp.Zkh7.Zj(Unknown Source)
	at burp.Zjr6.Zk(Unknown Source)
	at burp.Zo1w.lambda$issueRequest$0(Unknown Source)
	at burp.Zabq.ZL(Unknown Source)
	at burp.Zjrg.ZW(Unknown Source)
	at burp.Zjrg.Zz(Unknown Source)
	at burp.Za6d.ZK(Unknown Source)
	at burp.Zn1_.ZK(Unknown Source)
	at burp.Zo1w.Zi(Unknown Source)
	at burp.Zjd8.ZZ(Unknown Source)
	at burp.Za4l.Zi(Unknown Source)
	at burp.Zfkp.run(Unknown Source)
	at burp.Zf44.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by gh0stkey** [comment]
麻烦按模板提问题，而不是贴一长段报错，这样是无法定位问题的。
