### ISSUE TITLE
[BUG] 导入插件报错

### ISSUE THREAD

**Issue by lovechoudoufu** [gh0stkey/HaE#233]
## 使用环境

```
HaE 版本：4.0
有无自定义规则：无
BurpSuite 版本：2024.11.2
操作系统版本：ubuntu 24.04
是否阅读README：是
是否知晓注意事项：是
是否查阅历史ISSUE：是
```

## 问题详情

问题描述：
导入插件报错：

java.lang.NullPointerException: Cannot invoke "burp.api.montoya.core.Registration.isRegistered()" because "this.passiveHandler" is null
	at hae.component.Config.updateModeStatus(Config.java:382)
	at hae.component.Config.getModePanel(Config.java:141)
	at hae.component.Config.initComponents(Config.java:82)
	at hae.component.Config.<init>(Config.java:45)
	at hae.component.Main.initComponents(Main.java:60)
	at hae.component.Main.<init>(Main.java:25)
	at hae.HaE.initialize(HaE.java:37)
	at burp.Zxa_.Ze(Unknown Source)
	at burp.Zb58.Zi(Unknown Source)
	at burp.Zb5s.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
出现的场景：
导入插件

## 解决建议

无。

**Comment by lovechoudoufu** [comment]
打扰了，更新了最新版不报错了。
