### ISSUE TITLE
burp 2021.7.2 + hae 2.0.6 下显示异常

### ISSUE THREAD

**Issue by shadow1ng** [gh0stkey/HaE#25]
burp 2021.7.2 + hae 2.0.6 下。访问一会后，req和resp就没办法显示了
![image](https://user-images.githubusercontent.com/39651966/128161470-8a40b906-9cac-4616-9204-840359221a5e.png)
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at org.yaml.snakeyaml.scanner.ScannerImpl.getToken(ScannerImpl.java:281)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart.produce(ParserImpl.java:202)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:138)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at org.yaml.snakeyaml.util.ArrayStack.pop(ArrayStack.java:32)
	at org.yaml.snakeyaml.parser.ParserImpl.parseNode(ParserImpl.java:481)
	at org.yaml.snakeyaml.parser.ParserImpl.access$1400(ParserImpl.java:120)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockNode.produce(ParserImpl.java:395)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:113)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at org.yaml.snakeyaml.scanner.ScannerImpl.getToken(ScannerImpl.java:281)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart.produce(ParserImpl.java:202)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:138)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at org.yaml.snakeyaml.scanner.ScannerImpl.getToken(ScannerImpl.java:281)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart.produce(ParserImpl.java:202)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:138)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at org.yaml.snakeyaml.scanner.ScannerImpl.getToken(ScannerImpl.java:281)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart.produce(ParserImpl.java:202)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:175)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:138)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
	at burp.yaml.LoadConfigFile.getExcludeSuffix(LoadConfigFile.java:43)
	at burp.action.MatchHTTP.matchSuffix(MatchHTTP.java:16)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:81)
	at burp.cnv.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by sodmelody** [comment]
我也碰到了这样的问题。

**Comment by gh0stkey** [comment]
这个BUG是Burp官方的问题，上个月就联系官方在解决了，目前还没有出修复版本，等待官方解决吧。
![2021-08-05_10-36-33](https://user-images.githubusercontent.com/24655118/128282073-dcd43d31-70c6-4453-81da-e6a31b97b9c0.jpg)

**Comment by gh0stkey** [comment]
一个好消息：BurpSuite官方终于在2021.8.1版本中修复了插件扩展Tab的BUG，HaE可以正常使用了～
