### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 9

### ISSUE THREAD

**Issue by maybe-why-not** [gh0stkey/HaE#33]
### 环境
jdk 15.0, burp 2021.8, windows 10, HaE 2.0.6
### config.yaml
```
rules:
- rule:
  - color: red
    engine: nfa
    loaded: true
    name: ID card
    regex: '[^0-9]((\d{8}(0\d|10|11|12)([0-2]\d|30|31)\d{3}$)|(\d{6}(18|19|20)\d{2}(0[1-9]|10|11|12)([0-2]\d|30|31)\d{3}(\d|X|x)))[^0-9]'
    scope: response
  - color: red
    engine: nfa
    loaded: true
    name: phone
    regex: '[^0-9A-Za-z](1(3([0-35-9]\d|4[1-8])|4[14-9]\d|5([\d]\d|7[1-79])|66\d|7[2-35-8]\d|8\d{2}|9[89]\d)\d{7})[^0-9A-Za-z]'
    scope: response
  - color: red
    engine: nfa
    loaded: true
    name: shiro
    regex: (shiro)
    scope: response
  - color: red
    engine: nfa
    loaded: true
    name: axis2
    regex: (axis2)
    scope: response
  type: Basic Information
```
### response
```
18888888888
555555202109075555
axis2
shiro

```
### exception
```
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 9
	at burp.action.UpgradeColor.colorUpgrade(UpgradeColor.java:44)
	at burp.action.UpgradeColor.colorUpgrade(UpgradeColor.java:47)
	at burp.action.UpgradeColor.getEndColor(UpgradeColor.java:53)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:112)
	at burp.h7v.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

```
http history不能高亮
![image](https://user-images.githubusercontent.com/29968903/132350029-ac4229fc-21fb-48f8-b7b1-a54163d2dfa5.png)

**Comment by gh0stkey** [comment]
更新burp到最新版再尝试一下

**Comment by gh0stkey** [comment]
测试了下，确实是BUG，已经修复，马上推2.0.7版本，感谢！

**Comment by gh0stkey** [comment]
Release：https://github.com/gh0stkey/HaE/releases/tag/2.0.7
