### ISSUE TITLE
BURP

### ISSUE THREAD

**Issue by ChineseBoysGZ** [gh0stkey/HaE#37]
在burp中导入插件的时候，第一次导入成功之后，在config配置页面查看了之后，点击了一下reload `按钮，之后前边的rule页面就变的什么都没有了，关闭burp重新打开模块就消失了，之后在重新导入该插件，就一直报错，报错信息如下：org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at burp.yaml.LoadConfig.getRules(LoadConfig.java:116)
	at burp.ui.MainUI.initComponents(MainUI.java:178)
	at burp.ui.MainUI.<init>(MainUI.java:24)
	at burp.BurpExtender.<init>(BurpExtender.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.fpo.a(Unknown Source)
	at burp.fpo.<init>(Unknown Source)
	at burp.d25.a(Unknown Source)
	at burp.gix.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:162)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
	... 31 more
`
重新下载重新导入插件一直也没有导入成功，求解。

**Comment by 0Chencc** [comment]
好的，我看一下

**Comment by 0Chencc** [comment]
您能否把配置文件发一份给我呢

**Comment by 0Chencc** [comment]
你好，我筛查了一下会出现这种情况的原因：
burp本身没有对访问某些更高权限文件夹进行授权申请，假设你是mac用户，且你的配置文件在桌面或者文稿这类初始有隐私保护的文件夹，那么这些配置文件是无法被读取的，会被macos直接拦截，导致hae崩溃。
这个问题hae本身无法修复，这是burp的问题或者是burp提供的api的问题。您可以尝试把配置文件放到burp目录下并改名，然后再进行导入，我本地尝试了发现是可以顺利解决这个问题的。
您也不需要删除本插件，只需要在Setting.yml中将configPath这个字段的内容修改为：'Config.yml'（初始化配置文件路径）或者其他只是普通用户权限的文件夹中的配置文件路径即可。
