### ISSUE TITLE
两条rule同个颜色，不显示颜色

### ISSUE THREAD

**Issue by maybe-why-not** [gh0stkey/HaE#4]
![image](https://user-images.githubusercontent.com/29968903/95052615-d263c080-0721-11eb-839b-7fd3d6c72ed9.png)
![image](https://user-images.githubusercontent.com/29968903/95052665-ead3db00-0721-11eb-9ded-85d712c1a76b.png)
![image](https://user-images.githubusercontent.com/29968903/95052901-430add00-0722-11eb-9fb1-25d5b117fe1e.png)

`java.lang.IllegalArgumentException: unrecognized color
	at burp.fz.setHighlight(Unknown Source)
	at burp.bgb.setHighlight(Unknown Source)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:280)
	at burp.c6a.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: unrecognized color
	at burp.fz.setHighlight(Unknown Source)
	at burp.bgb.setHighlight(Unknown Source)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:280)
	at burp.c6a.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: unrecognized color
	at burp.fz.setHighlight(Unknown Source)
	at burp.bgb.setHighlight(Unknown Source)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:280)
	at burp.c6a.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: unrecognized color
	at burp.fz.setHighlight(Unknown Source)
	at burp.bgb.setHighlight(Unknown Source)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:280)
	at burp.c6a.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by gh0stkey** [comment]
Bug已经修复，1.1版本发布：https://github.com/gh0stkey/HaE/releases/tag/1.1，感谢，祝好运每一天😄
