### ISSUE TITLE
加载HaE报错

### ISSUE THREAD

**Issue by JohnRyk** [gh0stkey/HaE#41]
测试发现旧的Json配置文件版本的HaE都正常，从[HaE 2.0](https://github.com/gh0stkey/HaE/releases/tag/2.0) 以后的版本均报错。

org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at burp.yaml.LoadConfig.getRules(LoadConfig.java:115)
	at burp.ui.MainUI.initComponents(MainUI.java:178)
	at burp.ui.MainUI.<init>(MainUI.java:24)
	at burp.BurpExtender.<init>(BurpExtender.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at burp.z9.a(Unknown Source)
	at burp.z9.<init>(Unknown Source)
	at burp.f1g.a(Unknown Source)
	at burp.fjy.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:162)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
	... 31 more

**Comment by JohnRyk** [comment]
猜测是yaml解析器的问题，但不太熟悉，请指教。

**Comment by gh0stkey** [comment]
收到，这个需求我会考虑一下，请期待后续改进，感谢！
