### ISSUE TITLE
有人遇到过嘛，插件安装不上，换了几个jdk版本和HaE了

### ISSUE THREAD

**Issue by ccc996** [gh0stkey/HaE#43]
java.lang.ExceptionInInitializerError
	at burp.ui.MainUI.initComponents(MainUI.java:171)
	at burp.ui.MainUI.<init>(MainUI.java:25)
	at burp.BurpExtender.<init>(BurpExtender.java:18)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at burp.ftd.a(Unknown Source)
	at burp.ftd.<init>(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.kp.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at burp.yaml.LoadConfig.getRules(LoadConfig.java:115)
	at burp.Config.<clinit>(Config.java:42)
	... 16 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(Unknown Source)
	at java.base/java.io.PushbackInputStream.read(Unknown Source)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
	... 31 more

**Comment by gh0stkey** [comment]
检查一下配置文件的信息

**Comment by ccc996** [comment]
是指burp的配置么

**Comment by gh0stkey** [comment]
HaE的配置文件

**Comment by ccc996** [comment]
可以了，感谢解答！
