### ISSUE TITLE
jdk

### ISSUE THREAD

**Issue by JordanA54** [gh0stkey/HaE#59]

**Comment by JordanA54** [comment]
java.lang.NullPointerException
	at burp.yaml.LoadConfig.getConfigPath(LoadConfig.java:85)
	at burp.yaml.LoadConfig.getRules(LoadConfig.java:117)
	at burp.yaml.LoadConfig.<init>(LoadConfig.java:30)
	at burp.ui.MainUI.<init>(MainUI.java:22)
	at burp.BurpExtender.<init>(BurpExtender.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at burp.ete.a(Unknown Source)
	at burp.ete.<init>(Unknown Source)
	at burp.dgg.a(Unknown Source)
	at burp.ld.lambda$panelLoaded$0(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JordanA54** [comment]
师傅还想问一下配置文件在哪里看的，谢谢

**Comment by gh0stkey** [comment]
默认会创建在BurpSuite的jar包同级目录下

**Comment by JordanA54** [comment]
您好，我尝试了在windows下安装您的插件，安装没问题，生成的配置文件我也看到了，但是在mac下找不到是怎么回事呢？
报这个错
java.lang.NullPointerException
at burp.yaml.LoadConfig.getConfigPath(LoadConfig.java:85)
at burp.yaml.LoadConfig.getRules(LoadConfig.java:117)
at burp.yaml.LoadConfig.(LoadConfig.java:30)
at burp.ui.MainUI.(MainUI.java:22)
at burp.BurpExtender.(BurpExtender.java:19)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at burp.ete.a(Unknown Source)
at burp.ete.(Unknown Source)
at burp.dgg.a(Unknown Source)
at burp.ld.lambda$panelLoaded$0(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

> 默认会创建在BurpSuite的jar包同级目录下

**Comment by gh0stkey** [comment]
mac下是在burpsuite 这个app本身下面

**Comment by JordanA54** [comment]
> mac下是在burpsuite 这个app本身下面

您好，我确实没找到，安装失败代表着这个文件也不存在吧，那现在该怎么办呢，方便告诉一下嘛，万分感谢

**Comment by gh0stkey** [comment]
"/Applications/Burp Suite Professional.app/Contents/Resources/app/"，进这个目录就能看见

**Comment by JordanA54** [comment]
那可能是我的bp有问题了，没有/app/这个目录，谢谢了，最开始安装您的插件是可以安装的，后来我更改了下配置，加载了下配置文件，然后插件规则那里就空白了，我就卸载重装，现在就安装不上了

**Comment by gh0stkey** [comment]
bp版本是多少，可以换一下最新的版本

**Comment by gh0stkey** [comment]
加我微信吧，微信号: EVILCHEN__
