### ISSUE TITLE
插件无法初始化

### ISSUE THREAD

**Issue by wakaka6** [gh0stkey/HaE#64]
Burp输出日志
```txt
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.har.a(Unknown Source)
	at burp.har.<init>(Unknown Source)
	at burp.imo.a(Unknown Source)
	at burp._1.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Java版本
```txt
java 11.0.12 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```

Burp版本
```txt
Burp Suite professional V2022.3.8
```
HaE版本
```txt
HaE-2.2.3.jar
```

**Comment by gh0stkey** [comment]
可能是因为当前使用的是Java 8编译的程序，可以尝试在本机安装一个JDK8，或使用高版本JDK重打包Jar加载。

**Comment by wakaka6** [comment]
> 可能是因为当前使用的是Java 8编译的程序，可以尝试在本机安装一个JDK8，或使用高版本JDK重打包Jar加载。

师傅，能不能说一下怎么通过命令行打包jar包， 没怎么写过java， 另外我之前是因为新版burp用jdk8的少一些功能才升级的jdk11

**Comment by gh0stkey** [comment]
idea打开这个项目，然后使用gradle fatjar就可以打包了，记得修改JDK版本，或者你稍等我下班之后给你打包一个，可以加我微信，微信号: EVILCHEN__
