### ISSUE TITLE
重装java之后就报错，无法加载插件

### ISSUE THREAD

**Issue by KingXS** [gh0stkey/HaE#77]
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1198)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:213)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:140)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at burp.yaml.LoadConfig.getRules(LoadConfig.java:132)
	at burp.yaml.LoadConfig.<init>(LoadConfig.java:36)
	at burp.ui.MainUI.<init>(MainUI.java:25)
	at burp.BurpExtender.<init>(BurpExtender.java:22)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at burp.etx.a(Unknown Source)
	at burp.etx.<init>(Unknown Source)
	at burp.a3y.a(Unknown Source)
	at burp.c4c.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:162)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:92)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:124)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)
	... 31 more

**Comment by KingXS** [comment]
java版本
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

burpsuite版本
2022.3.6

HAE版本
2.4.1

**Comment by gh0stkey** [comment]
这是因为配置文件导致的，可以找一下你的配置文件，看看内容是否出现问题
