### ISSUE TITLE
最新版burp报错

### ISSUE THREAD

**Issue by apsry** [gh0stkey/HaE#86]
mac
java.lang.Exception: Extension class is not a recognized type
	at burp.rni.v(Unknown Source)
	at burp.rni.<init>(Unknown Source)
	at burp.tns.W(Unknown Source)
	at burp.zuy.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

好像是burp更新，官方检查了加载。。。
https://forum.portswigger.net/thread/my-burp-extension-stopped-working-since-the-latest-burp-update-6a400ef7

**Comment by gh0stkey** [comment]
啥版本的Burp我似乎没有出现这个问题

**Comment by gh0stkey** [comment]
看了下你给的链接中的这个插件，他的修复方式就是加了一个IBurpExtender，但是我的代码中本来就有这个：
https://github.com/honoki/bbrf-burp-plugin/commit/d37b1ce88e260a2a2090bff93e735c36e8b99e3c#diff-66d2b45bffc03151ec5c3bd47c6e4bce07861783e687c752edd4b85bf92cfd33

**Comment by apsry** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/55017061/202381859-a09b40dd-7761-4a53-a38a-495529556e34.png">
我用的是这个版本，自带的java
<img width="350" alt="image" src="https://user-images.githubusercontent.com/55017061/202382145-c8c5c362-e7a8-4ae8-9caf-51c856c30edd.png">
应该是我的环境问题0.0

**Comment by gh0stkey** [comment]
切到2022.11.1试试

**Comment by Stowaway-y** [comment]
2022.11.1也有问题
java.lang.NullPointerException
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:45)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
	at burp.pjo.isEnabledFor(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.s2p.invoke(Unknown Source)
	at com.sun.proxy.$Proxy86.isEnabledFor(Unknown Source)
	at burp.cky.Y(Unknown Source)
	at burp.byk.e(Unknown Source)
	at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at burp.r8.U(Unknown Source)
	at burp.r8.f(Unknown Source)
	at burp.s12.L(Unknown Source)
	at burp.s12.u(Unknown Source)
	at burp.s12.y(Unknown Source)
	at burp.mki.L(Unknown Source)
	at burp.tnz.v(Unknown Source)
	at burp.tnz.F(Unknown Source)
	at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:45)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
	at burp.pjo.isEnabledFor(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.s2p.invoke(Unknown Source)
	at com.sun.proxy.$Proxy86.isEnabledFor(Unknown Source)
	at burp.cky.Y(Unknown Source)
	at burp.byk.e(Unknown Source)
	at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at burp.r8.U(Unknown Source)
	at burp.r8.f(Unknown Source)
	at burp.s12.L(Unknown Source)
	at burp.s12.u(Unknown Source)
	at burp.s12.y(Unknown Source)
	at burp.mki.n(Unknown Source)
	at burp.tnz.J(Unknown Source)
	at burp.tnz.F(Unknown Source)
	at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
	at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
	at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:66)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
	at burp.wkk.isEnabledFor(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.s2p.invoke(Unknown Source)
	at com.sun.proxy.$Proxy87.isEnabledFor(Unknown Source)
	at burp.zdq.i(Unknown Source)
	at burp.by8.e(Unknown Source)
	at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at burp.r8.U(Unknown Source)
	at burp.r8.f(Unknown Source)
	at burp.s12.L(Unknown Source)
	at burp.s12.u(Unknown Source)
	at burp.s12.y(Unknown Source)
	at burp.mki.n(Unknown Source)
	at burp.tnz.J(Unknown Source)
	at burp.tnz.F(Unknown Source)
	at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
