### ISSUE TITLE
burp 2022.11.1报错

### ISSUE THREAD

**Issue by Stowaway-y** [gh0stkey/HaE#87]
burp版本：2022.11.1
jdk：14
Hae：2.4.4J9
报错信息：
java.lang.NullPointerException
at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:45)
at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
at burp.pjo.isEnabledFor(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at burp.s2p.invoke(Unknown Source)
at com.sun.proxy.$Proxy86.isEnabledFor(Unknown Source)
at burp.cky.Y(Unknown Source)
at burp.byk.e(Unknown Source)
at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at burp.r8.U(Unknown Source)
at burp.r8.f(Unknown Source)
at burp.s12.L(Unknown Source)
at burp.s12.u(Unknown Source)
at burp.s12.y(Unknown Source)
at burp.mki.L(Unknown Source)
at burp.tnz.v(Unknown Source)
at burp.tnz.F(Unknown Source)
at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:45)
at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
at burp.pjo.isEnabledFor(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at burp.s2p.invoke(Unknown Source)
at com.sun.proxy.$Proxy86.isEnabledFor(Unknown Source)
at burp.cky.Y(Unknown Source)
at burp.byk.e(Unknown Source)
at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at burp.r8.U(Unknown Source)
at burp.r8.f(Unknown Source)
at burp.s12.L(Unknown Source)
at burp.s12.u(Unknown Source)
at burp.s12.y(Unknown Source)
at burp.mki.n(Unknown Source)
at burp.tnz.J(Unknown Source)
at burp.tnz.F(Unknown Source)
at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
at burp.action.ExtractContent.lambda$matchRegex$0(ExtractContent.java:34)
at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1011)
at burp.action.ExtractContent.matchRegex(ExtractContent.java:21)
at burp.action.ProcessMessage.processMessageByContent(ProcessMessage.java:66)
at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:146)
at burp.wkk.isEnabledFor(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at burp.s2p.invoke(Unknown Source)
at com.sun.proxy.$Proxy87.isEnabledFor(Unknown Source)
at burp.zdq.i(Unknown Source)
at burp.by8.e(Unknown Source)
at burp.s12.lambda$updateVisiblePanes$1(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at burp.r8.U(Unknown Source)
at burp.r8.f(Unknown Source)
at burp.s12.L(Unknown Source)
at burp.s12.u(Unknown Source)
at burp.s12.y(Unknown Source)
at burp.mki.n(Unknown Source)
at burp.tnz.J(Unknown Source)
at burp.tnz.F(Unknown Source)
at burp.tnz.lambda$extensionConfigChanged$4(Unknown Source)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by gh0stkey** [comment]
请检查你的配置文件哈，这种一般都是配置文件出了问题，或者正则写错了。

**Comment by Stowaway-y** [comment]
确实是，感谢key师傅
